package com.tictactoe.domain.models

enum class VictoryType {

    HORIZONTAL_TOP, HORIZONTAL_MIDDLE, HORIZONTAL_BOTTOM,
    VERTICAL_LEFT, VERTICAL_MIDDLE, VERTICAL_RIGHT,
    DIAGONAL_RIGHT, DIAGONAL_LEFT,
    DRAW
}
